# Generated by Django 4.0.4 on 2022-05-02 08:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type_ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Video', 'Video'), ('Article', 'Article')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2022, 5, 2, 8, 21, 34, 986920, tzinfo=utc))),
                ('lien', models.URLField(max_length=300)),
                ('key_word', models.CharField(max_length=100, null=True)),
                ('ressource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_veille.type_ressource')),
            ],
        ),
    ]
