# Generated by Django 4.0.4 on 2022-05-02 08:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_veille', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 2, 8, 29, 35, 151338, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='key_word',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
