# Generated by Django 4.0.4 on 2022-05-03 12:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_veille', '0002_alter_ressource_date_alter_ressource_key_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='titre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ressource',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 3, 12, 19, 26, 477137, tzinfo=utc)),
        ),
    ]
