# Generated by Django 4.0.4 on 2022-05-04 09:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_veille', '0003_ressource_titre_alter_ressource_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 4, 9, 9, 5, 753405, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='lien',
            field=models.TextField(max_length=300),
        ),
    ]
