# Generated by Django 4.0.4 on 2022-05-04 09:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_veille', '0004_alter_ressource_date_alter_ressource_lien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 4, 9, 12, 29, 863547, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='lien',
            field=models.URLField(max_length=300),
        ),
    ]
