# Generated by Django 4.0.4 on 2022-05-12 13:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_veille', '0005_alter_ressource_date_alter_ressource_lien'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='corpus',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 12, 13, 51, 58, 650085, tzinfo=utc)),
        ),
    ]
