# Generated by Django 4.0.4 on 2022-05-12 13:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_veille', '0006_ressource_corpus_alter_ressource_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='corpus',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 12, 13, 56, 24, 139278, tzinfo=utc)),
        ),
    ]
