# Generated by Django 4.0.4 on 2022-05-13 12:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_veille', '0008_ressource_user_alter_ressource_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 13, 12, 47, 30, 810120, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
